const mongoose=require('mongoose');

const UserSchema=mongoose.Schema({
    firstName:{
        type:String,
        require:true,
        trim:true
    },
    lastName:{
        type:String,
        require:true,
        trim:true
    },
    email:{
        type:String,
        require:true,
        trim:true
    },
    password:{
        type:String,
        require:true
    },
    accountType:{
        type:String,
        enum:["Admin","Student","Instructor"],
        require:true
    },
    active:{
        type:Boolean,
        default:false
    },
    approve:{
        type:Boolean,
        default:false
    },
    courses:[{
        type:mongoose.Schema.Types.ObjectId,
        ref:'Courses'
    }],
    profile:{
        type:mongoose.Schema.Types.ObjectId,
        ref:"UserProfile"
    },
    courseProgress:[{
        type:mongoose.Schema.Types.ObjectId,
        ref:'CourseProgress'
    }]
});

module.exports=mongoose.model('User',UserSchema);